---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
      version: 2.4.0
  releaseName: keda
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: keda
  storageNamespace: keda

