---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.0.6
  releaseName: ingress-nginx
  dependsOn: []
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 1m0s
  targetNamespace: ingress-nginx
  storageNamespace: ingress-nginx
  values:
    controller:
      hostPort:
        enabled: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
      nodeSelector:
        kubernetes.io/os: linux
        ingress-ready: "verdade"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          scrapeInterval: 30s
      service:
        type: NodePort
    defaultBackend:
      enabled: true
